<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>The Part module &mdash; FreeCAD API documentation</title>
    
    <link rel="stylesheet" href="_static/freecad.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    './',
        VERSION:     '0.14',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <link rel="shortcut icon" href="_static/favicon.ico"/>
    <link rel="top" title="FreeCAD API documentation" href="index.html" />
    <link rel="next" title="The Sketcher module" href="Sketch.html" />
    <link rel="prev" title="The Mesh module" href="Mesh.html" /> 
  </head>
  <body>
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="Sketch.html" title="The Sketcher module"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="Mesh.html" title="The Mesh module"
             accesskey="P">previous</a> |</li>
        <li><a href="index.html">FreeCAD API documentation</a> &raquo;</li> 
      </ul>
    </div>  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body">
            
  <div class="section" id="the-part-module">
<h1>The Part module<a class="headerlink" href="#the-part-module" title="Permalink to this headline">¶</a></h1>
<div class="toctree-wrapper compound">
<ul class="simple">
</ul>
</div>
<span class="target" id="module-Part"></span><p>This is a module working with shapes.</p>
<dl class="attribute">
<dt id="Part.Arc">
<tt class="descname">Arc</tt><a class="headerlink" href="#Part.Arc" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomTrimmedCurve</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.ArcOfCircle">
<tt class="descname">ArcOfCircle</tt><a class="headerlink" href="#Part.ArcOfCircle" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomArcOfCircle</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.BSplineCurve">
<tt class="descname">BSplineCurve</tt><a class="headerlink" href="#Part.BSplineCurve" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomBSplineCurve</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.BSplineSurface">
<tt class="descname">BSplineSurface</tt><a class="headerlink" href="#Part.BSplineSurface" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomBSplineSurface</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.BezierCurve">
<tt class="descname">BezierCurve</tt><a class="headerlink" href="#Part.BezierCurve" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomBezierCurve</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.BezierSurface">
<tt class="descname">BezierSurface</tt><a class="headerlink" href="#Part.BezierSurface" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomBezierSurface</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Circle">
<tt class="descname">Circle</tt><a class="headerlink" href="#Part.Circle" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomCircle</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.CompSolid">
<tt class="descname">CompSolid</tt><a class="headerlink" href="#Part.CompSolid" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">TopoShape</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Compound">
<tt class="descname">Compound</tt><a class="headerlink" href="#Part.Compound" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">TopoShape</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Cone">
<tt class="descname">Cone</tt><a class="headerlink" href="#Part.Cone" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomCone</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Cylinder">
<tt class="descname">Cylinder</tt><a class="headerlink" href="#Part.Cylinder" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomCylinder</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Edge">
<tt class="descname">Edge</tt><a class="headerlink" href="#Part.Edge" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">TopoShape</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Ellipse">
<tt class="descname">Ellipse</tt><a class="headerlink" href="#Part.Ellipse" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomEllipse</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Face">
<tt class="descname">Face</tt><a class="headerlink" href="#Part.Face" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">TopoShape</span></tt></p>
</dd></dl>

<dl class="class">
<dt id="Part.Feature">
<em class="property">class </em><tt class="descname">Feature</tt><a class="headerlink" href="#Part.Feature" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <tt class="xref py py-class docutils literal"><span class="pre">App.DocumentObject</span></tt></p>
<p>This is the father of all shape object classes</p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Hyperbola">
<tt class="descname">Hyperbola</tt><a class="headerlink" href="#Part.Hyperbola" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomHyperbola</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Line">
<tt class="descname">Line</tt><a class="headerlink" href="#Part.Line" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomLineSegment</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Parabola">
<tt class="descname">Parabola</tt><a class="headerlink" href="#Part.Parabola" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomParabola</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Plane">
<tt class="descname">Plane</tt><a class="headerlink" href="#Part.Plane" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomPlane</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Point">
<tt class="descname">Point</tt><a class="headerlink" href="#Part.Point" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomPoint</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.RectangularTrimmedSurface">
<tt class="descname">RectangularTrimmedSurface</tt><a class="headerlink" href="#Part.RectangularTrimmedSurface" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomTrimmedSurface</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Shape">
<tt class="descname">Shape</tt><a class="headerlink" href="#Part.Shape" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">TopoShape</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Shell">
<tt class="descname">Shell</tt><a class="headerlink" href="#Part.Shell" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">TopoShape</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Solid">
<tt class="descname">Solid</tt><a class="headerlink" href="#Part.Solid" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">TopoShape</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Sphere">
<tt class="descname">Sphere</tt><a class="headerlink" href="#Part.Sphere" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomSphere</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.SurfaceOfExtrusion">
<tt class="descname">SurfaceOfExtrusion</tt><a class="headerlink" href="#Part.SurfaceOfExtrusion" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomSurfaceOfExtrusion</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.SurfaceOfRevolution">
<tt class="descname">SurfaceOfRevolution</tt><a class="headerlink" href="#Part.SurfaceOfRevolution" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomSurfaceOfRevolution</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Toroid">
<tt class="descname">Toroid</tt><a class="headerlink" href="#Part.Toroid" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">GeomToroid</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Vertex">
<tt class="descname">Vertex</tt><a class="headerlink" href="#Part.Vertex" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">TopoShape</span></tt></p>
</dd></dl>

<dl class="attribute">
<dt id="Part.Wire">
<tt class="descname">Wire</tt><a class="headerlink" href="#Part.Wire" title="Permalink to this definition">¶</a></dt>
<dd><p>alias of <tt class="xref py py-class docutils literal"><span class="pre">TopoShape</span></tt></p>
</dd></dl>

<dl class="function">
<dt id="Part.cast_to_shape">
<tt class="descname">cast_to_shape</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.cast_to_shape" title="Permalink to this definition">¶</a></dt>
<dd><p>cast_to_shape(shape) &#8211; Cast to the actual shape type</p>
</dd></dl>

<dl class="function">
<dt id="Part.export">
<tt class="descname">export</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.export" title="Permalink to this definition">¶</a></dt>
<dd><p>export(list,string) &#8211; Export a list of objects into a single file.</p>
</dd></dl>

<dl class="function">
<dt id="Part.exportUnits">
<tt class="descname">exportUnits</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.exportUnits" title="Permalink to this definition">¶</a></dt>
<dd><p>exportUnits([string=MM|M|IN]) &#8211; Set units for exporting STEP/IGES files and returns the units.</p>
</dd></dl>

<dl class="function">
<dt id="Part.getSortedClusters">
<tt class="descname">getSortedClusters</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.getSortedClusters" title="Permalink to this definition">¶</a></dt>
<dd><p>getSortedClusters(list of edges) &#8211; Helper method to sort and cluster a variety of edges</p>
</dd></dl>

<dl class="function">
<dt id="Part.insert">
<tt class="descname">insert</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.insert" title="Permalink to this definition">¶</a></dt>
<dd><p>insert(string,string) &#8211; Insert the file into the given document.</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeBox">
<tt class="descname">makeBox</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeBox" title="Permalink to this definition">¶</a></dt>
<dd><p>makeBox(length,width,height,[pnt,dir]) &#8211; Make a box located
in pnt with the dimensions (length,width,height)
By default pnt=Vector(0,0,0) and dir=Vector(0,0,1)</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeCircle">
<tt class="descname">makeCircle</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeCircle" title="Permalink to this definition">¶</a></dt>
<dd><p>makeCircle(radius,[pnt,dir,angle1,angle2]) &#8211; Make a circle with a given radius
By default pnt=Vector(0,0,0), dir=Vector(0,0,1), angle1=0 and angle2=360</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeCompound">
<tt class="descname">makeCompound</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeCompound" title="Permalink to this definition">¶</a></dt>
<dd><p>makeCompound(list) &#8211; Create a compound out of a list of shapes.</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeCone">
<tt class="descname">makeCone</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeCone" title="Permalink to this definition">¶</a></dt>
<dd><p>makeCone(radius1,radius2,height,[pnt,dir,angle]) &#8211; Make a cone with given radii and height
By default pnt=Vector(0,0,0), dir=Vector(0,0,1) and angle=360</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeCylinder">
<tt class="descname">makeCylinder</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeCylinder" title="Permalink to this definition">¶</a></dt>
<dd><p>makeCylinder(radius,height,[pnt,dir,angle]) &#8211; Make a cylinder with a given radius and height
By default pnt=Vector(0,0,0),dir=Vector(0,0,1) and angle=360</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeFilledFace">
<tt class="descname">makeFilledFace</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeFilledFace" title="Permalink to this definition">¶</a></dt>
<dd><p>makeFilledFace(list) &#8211; Create a face out of a list of edges.</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeHelix">
<tt class="descname">makeHelix</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeHelix" title="Permalink to this definition">¶</a></dt>
<dd><p>makeHelix(pitch,height,radius,[angle]) &#8211; Make a helix with a given pitch, height and radius
By default a cylindrical surface is used to create the helix. If the fourth parameter is set
(the apex given in degree) a conical surface is used instead</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeLine">
<tt class="descname">makeLine</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeLine" title="Permalink to this definition">¶</a></dt>
<dd><p>makeLine((x1,y1,z1),(x2,y2,z2)) &#8211; Make a line of two points</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeLoft">
<tt class="descname">makeLoft</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeLoft" title="Permalink to this definition">¶</a></dt>
<dd><p>makeLoft(list of wires) &#8211; Create a loft shape.</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeLongHelix">
<tt class="descname">makeLongHelix</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeLongHelix" title="Permalink to this definition">¶</a></dt>
<dd><p>makeLongHelix(pitch,height,radius,[angle],[hand]) &#8211; Make a (multi-edge) helix with a given pitch, height and radius
By default a cylindrical surface is used to create the helix. If the fourth parameter is set
(the apex given in degree) a conical surface is used instead.</p>
</dd></dl>

<dl class="function">
<dt id="Part.makePlane">
<tt class="descname">makePlane</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makePlane" title="Permalink to this definition">¶</a></dt>
<dd><p>makePlane(length,width,[pnt,dir]) &#8211; Make a plane
By default pnt=Vector(0,0,0) and dir=Vector(0,0,1)</p>
</dd></dl>

<dl class="function">
<dt id="Part.makePolygon">
<tt class="descname">makePolygon</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makePolygon" title="Permalink to this definition">¶</a></dt>
<dd><p>makePolygon(list) &#8211; Make a polygon of a list of points</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeRevolution">
<tt class="descname">makeRevolution</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeRevolution" title="Permalink to this definition">¶</a></dt>
<dd><p>makeRevolution(Curve,[vmin,vmax,angle,pnt,dir,shapetype]) &#8211; Make a revolved shape
by rotating the curve or a portion of it around an axis given by (pnt,dir).
By default vmin/vmax=bounds of the curve,angle=360,pnt=Vector(0,0,0) and
dir=Vector(0,0,1) and shapetype=Part.Solid</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeRuledSurface">
<tt class="descname">makeRuledSurface</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeRuledSurface" title="Permalink to this definition">¶</a></dt>
<dd><p>makeRuledSurface(Edge|Wire,Edge|Wire) &#8211; Make a ruled surface
Create a ruled surface out of two edges or wires. If wires are used thenthese must have the same number of edges.</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeShell">
<tt class="descname">makeShell</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeShell" title="Permalink to this definition">¶</a></dt>
<dd><p>makeShell(list) &#8211; Create a shell out of a list of faces.</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeSolid">
<tt class="descname">makeSolid</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeSolid" title="Permalink to this definition">¶</a></dt>
<dd><p>makeSolid(shape) &#8211; Create a solid out of the shells inside a shape.</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeSphere">
<tt class="descname">makeSphere</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeSphere" title="Permalink to this definition">¶</a></dt>
<dd><p>makeSphere(radius,[pnt, dir, angle1,angle2,angle3]) &#8211; Make a sphere with a given radius
By default pnt=Vector(0,0,0), dir=Vector(0,0,1), angle1=0, angle2=90 and angle3=360</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeSweepSurface">
<tt class="descname">makeSweepSurface</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeSweepSurface" title="Permalink to this definition">¶</a></dt>
<dd><p>makeSweepSurface(edge(path),edge(profile),[float]) &#8211; Create a profile along a path.</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeThread">
<tt class="descname">makeThread</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeThread" title="Permalink to this definition">¶</a></dt>
<dd><p>makeThread(pitch,depth,height,radius) &#8211; Make a thread with a given pitch, depth, height and radius</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeTorus">
<tt class="descname">makeTorus</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeTorus" title="Permalink to this definition">¶</a></dt>
<dd><p>makeTorus(radius1,radius2,[pnt,dir,angle1,angle2,angle]) &#8211; Make a torus with a given radii and angles
By default pnt=Vector(0,0,0),dir=Vector(0,0,1),angle1=0,angle1=360 and angle=360</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeTube">
<tt class="descname">makeTube</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeTube" title="Permalink to this definition">¶</a></dt>
<dd><p>makeTube(edge,radius,[continuity,max degree,max segments]) &#8211; Create a tube.
continuity is a string which must be &#8216;C0&#8217;,&#8217;C1&#8217;,&#8217;C2&#8217;,&#8217;C3&#8217;,&#8217;CN&#8217;,&#8217;G1&#8217; or &#8216;G1&#8217;,</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeWedge">
<tt class="descname">makeWedge</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeWedge" title="Permalink to this definition">¶</a></dt>
<dd><p>makeWedge(xmin, ymin, zmin, z2min, x2min,
xmax, ymax, zmax, z2max, x2max,[pnt,dir])</p>
<blockquote>
<div>&#8211; Make a wedge located in pnt</div></blockquote>
<p>By default pnt=Vector(0,0,0) and dir=Vector(0,0,1)</p>
</dd></dl>

<dl class="function">
<dt id="Part.makeWireString">
<tt class="descname">makeWireString</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.makeWireString" title="Permalink to this definition">¶</a></dt>
<dd><p>makeWireString(string,fontdir,fontfile,height,[track]) &#8211; Make list of wires in the form of a string&#8217;s characters.</p>
</dd></dl>

<dl class="function">
<dt id="Part.open">
<tt class="descname">open</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.open" title="Permalink to this definition">¶</a></dt>
<dd><p>open(string) &#8211; Create a new document and load the file into the document.</p>
</dd></dl>

<dl class="function">
<dt id="Part.read">
<tt class="descname">read</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.read" title="Permalink to this definition">¶</a></dt>
<dd><p>read(string) &#8211; Load the file and return the shape.</p>
</dd></dl>

<dl class="function">
<dt id="Part.setStaticValue">
<tt class="descname">setStaticValue</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.setStaticValue" title="Permalink to this definition">¶</a></dt>
<dd><p>setStaticValue(string,string|int|float) &#8211; Set a name to a value The value can be a string, int or float.</p>
</dd></dl>

<dl class="function">
<dt id="Part.show">
<tt class="descname">show</tt><big>(</big><big>)</big><a class="headerlink" href="#Part.show" title="Permalink to this definition">¶</a></dt>
<dd><p>show(shape) &#8211; Add the shape to the active document or create one if no document exists.</p>
</dd></dl>

</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar">
        <div class="sphinxsidebarwrapper">
  <h4>Previous topic</h4>
  <p class="topless"><a href="Mesh.html"
                        title="previous chapter">The Mesh module</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="Sketch.html"
                        title="next chapter">The Sketcher module</a></p>
  <h3>This Page</h3>
  <ul class="this-page-menu">
    <li><a href="_sources/Part.txt"
           rel="nofollow">Show Source</a></li>
  </ul>
<div id="searchbox" style="display: none">
  <h3>Quick search</h3>
    <form class="search" action="search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    <p class="searchtip" style="font-size: 90%">
    Enter search terms or a module, class or function name.
    </p>
  <p>
	  <a href="http://www.freecadweb.org">Go back to the FreeCAD homepage</a>
  </p>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="py-modindex.html" title="Python Module Index"
             >modules</a> |</li>
        <li class="right" >
          <a href="Sketch.html" title="The Sketcher module"
             >next</a> |</li>
        <li class="right" >
          <a href="Mesh.html" title="The Mesh module"
             >previous</a> |</li>
        <li><a href="index.html">FreeCAD API documentation</a> &raquo;</li> 
      </ul>
    </div>
    <div class="footer">
        &copy; Copyright 2013, Jürgen Riegel, Werner Mayer, Yorik van Havre.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.2.2.
    </div>
  </body>
</html>